# Generated by Django 5.1 on 2024-10-02 10:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="post_audios/",
                validators=[blog.models.validate_media_file],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post_images/",
                validators=[blog.models.validate_media_file],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="post_videos/",
                validators=[blog.models.validate_media_file],
            ),
        ),
    ]
