# Generated by Django 5.1 on 2024-10-02 10:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_audio_post_image_post_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="post_media/",
                validators=[blog.models.validate_media_file],
            ),
        ),
    ]
